CREATE TABLE usuario (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(30) NOT NULL DEFAULT 'USER' CHECK (tipo_usuario IN ('USER', 'ADMIN', 'SUPER')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
