CREATE TABLE super_admin (
    id BIGSERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    tipo_usuario VARCHAR(30) NOT NULL DEFAULT 'SUPER' CHECK (tipo_usuario IN ('SUPER')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
